

on:
  push:
    branches: [master]
  schedule:
    # https://crontab.guru/once-a-day
    - cron: "* * * * *"

# This is a basic workflow to help you get started with Actions

name: CHRON

jobs:
  chron:
    env:
      API_KEY: ${{ secrets.API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Execute an Algorithm request
        run: |
          curl --request POST \
          --url https://api.algorithmia.com/v1/algo/demo/hello?timeout=300 \
          --header 'Authorization: Simple ${{secrets.API_KEY}}' \
          --header 'content-type: application/json' \
          --data '"chron"' \
          --fail
