# This is a basic workflow to help you get started with Actions

name: CHRON

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  chron:
    env:
      API_KEY: ${{ secrets.API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Execute an Algorithm request
        run: |
          curl --request POST \
          --url https://api.algorithmia.com/v1/algo/demo/hello?timeout=300 \
          --header 'Authorization: Simple ${{secrets.API_KEY}}' \
          --header 'content-type: application/json' \
          --data '"chron"' \
          --fail
